package com.classmate.core.audio

import com.classmate.core.ai.AiExecutionSource
import com.classmate.core.exporting.StudyReport

data class CourseEssenceScript(
    val opening: String,
    val keyPoints: List<String>,
    val weakPoints: List<String>,
    val reviewReminders: List<String>,
    val closing: String,
    val source: AiExecutionSource = AiExecutionSource.SAFE_PLACEHOLDER,
) {
    fun toPlainText(): String = buildString {
        appendLine(opening)
        appendLine()
        appendLine("Key points")
        keyPoints.forEachIndexed { index, item -> appendLine("${index + 1}. $item") }
        if (weakPoints.isNotEmpty()) {
            appendLine()
            appendLine("Weak points")
            weakPoints.forEachIndexed { index, item -> appendLine("${index + 1}. $item") }
        }
        if (reviewReminders.isNotEmpty()) {
            appendLine()
            appendLine("Review reminders")
            reviewReminders.forEachIndexed { index, item -> appendLine("${index + 1}. $item") }
        }
        appendLine()
        appendLine(closing)
    }.trim()
}

enum class CourseEssenceAudioStatus { AUDIO_READY, SCRIPT_ONLY_CONFIG_MISSING, FAILED }

data class CourseEssenceAudioResult(
    val status: CourseEssenceAudioStatus,
    val script: CourseEssenceScript,
    val audioBytes: ByteArray? = null,
    val fileName: String? = null,
    val source: AiExecutionSource = AiExecutionSource.SAFE_PLACEHOLDER,
    val message: String,
) {
    val hasAudio: Boolean get() = audioBytes?.isNotEmpty() == true
}

interface TtsProvider {
    fun synthesize(script: CourseEssenceScript): CourseEssenceAudioResult
}

class ConfigMissingTtsProvider : TtsProvider {
    override fun synthesize(script: CourseEssenceScript): CourseEssenceAudioResult =
        CourseEssenceAudioResult(
            status = CourseEssenceAudioStatus.SCRIPT_ONLY_CONFIG_MISSING,
            script = script,
            source = AiExecutionSource.MANUAL,
            message = "TTS provider is not configured; exported script text is available.",
        )
}

class FakeTtsProvider(
    private val bytes: ByteArray = "FAKE_AUDIO".toByteArray(),
) : TtsProvider {
    override fun synthesize(script: CourseEssenceScript): CourseEssenceAudioResult =
        CourseEssenceAudioResult(
            status = CourseEssenceAudioStatus.AUDIO_READY,
            script = script.copy(source = AiExecutionSource.CLOUD),
            audioBytes = bytes,
            fileName = "course-essence-audio.bin",
            source = AiExecutionSource.CLOUD,
            message = "Audio generated by configured TTS provider.",
        )
}

object CourseEssenceAudioExporter {
    fun buildScript(report: StudyReport, source: AiExecutionSource = AiExecutionSource.SAFE_PLACEHOLDER): CourseEssenceScript {
        val keyPoints = report.knowledgePoints
            .take(6)
            .map { "${it.title}: ${it.summary}" }
            .ifEmpty { report.overview.take(6) }
        val weakPoints = report.needPractice.take(5).map { "${it.title}: ${it.reason}" }
        val review = buildList {
            if (report.review.dueToday.isNotEmpty()) add("Today: ${report.review.dueToday.joinToString(", ")}")
            if (report.review.needsRecheck.isNotEmpty()) add("Check evidence: ${report.review.needsRecheck.joinToString(", ")}")
            if (report.practice != null) add("Practice next step: ${report.practice.nextSuggestion}")
        }
        return CourseEssenceScript(
            opening = "This is a ClassMate course essence review for ${report.courseTitle}.",
            keyPoints = keyPoints,
            weakPoints = weakPoints,
            reviewReminders = review,
            closing = "Use this audio script as a review aid, and verify details against the lesson evidence.",
            source = source,
        )
    }

    fun generate(report: StudyReport, provider: TtsProvider): CourseEssenceAudioResult =
        provider.synthesize(buildScript(report))
}
