package com.classmate.core.audio

import com.classmate.core.ai.AiExecutionSource
import com.classmate.core.capture.CaptureHttpResponse
import com.classmate.core.capture.CaptureProviderConfig
import com.classmate.core.capture.CaptureTransport
import com.classmate.core.capture.CaptureTransportNotConfigured
import com.classmate.core.capture.NotConfiguredCaptureTransport
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject

class VivoTtsProvider(
    private val config: CaptureProviderConfig = CaptureProviderConfig.ABSENT,
    private val transport: CaptureTransport = NotConfiguredCaptureTransport,
    private val timeoutMs: Long = 30_000,
) : TtsProvider {
    override fun synthesize(script: CourseEssenceScript): CourseEssenceAudioResult {
        if (!config.isConfigured) return ConfigMissingTtsProvider().synthesize(script)
        val text = script.toPlainText()
        if (text.isBlank()) {
            return CourseEssenceAudioResult(
                status = CourseEssenceAudioStatus.FAILED,
                script = script,
                source = AiExecutionSource.SAFE_PLACEHOLDER,
                message = "Course essence script is empty.",
            )
        }
        return try {
            parseResponse(script, transport.postJson(url(), headers(), body(text), timeoutMs))
        } catch (_: CaptureTransportNotConfigured) {
            ConfigMissingTtsProvider().synthesize(script)
        } catch (_: Exception) {
            CourseEssenceAudioResult(
                status = CourseEssenceAudioStatus.FAILED,
                script = script,
                source = AiExecutionSource.SAFE_PLACEHOLDER,
                message = "TTS request failed; script-only export remains available.",
            )
        }
    }

    fun parseResponse(script: CourseEssenceScript, response: CaptureHttpResponse): CourseEssenceAudioResult {
        if (response.status !in 200..299) {
            return CourseEssenceAudioResult(
                status = CourseEssenceAudioStatus.FAILED,
                script = script,
                source = AiExecutionSource.SAFE_PLACEHOLDER,
                message = "TTS service returned a non-success status; script-only export remains available.",
            )
        }
        val root = parseObject(response.body)
        val code = root?.str("code") ?: root?.str("error_code") ?: "0"
        if (code != "0" && !code.equals("success", ignoreCase = true)) {
            return CourseEssenceAudioResult(
                status = CourseEssenceAudioStatus.FAILED,
                script = script,
                source = AiExecutionSource.SAFE_PLACEHOLDER,
                message = "TTS service did not return an audio payload.",
            )
        }
        val data = root?.obj("data") ?: root
        val audioText = data?.str("audio") ?: data?.str("audioData") ?: data?.str("audioContent") ?: data?.str("audio_url")
        if (audioText.isNullOrBlank()) {
            return CourseEssenceAudioResult(
                status = CourseEssenceAudioStatus.FAILED,
                script = script,
                source = AiExecutionSource.SAFE_PLACEHOLDER,
                message = "TTS response had no audio payload; script-only export remains available.",
            )
        }
        return CourseEssenceAudioResult(
            status = CourseEssenceAudioStatus.AUDIO_READY,
            script = script.copy(source = AiExecutionSource.CLOUD),
            audioBytes = audioText.toByteArray(Charsets.UTF_8),
            fileName = "course-essence-audio.mp3",
            source = AiExecutionSource.CLOUD,
            message = "Course essence audio generated by configured TTS provider.",
        )
    }

    private fun url(): String = "https://${config.domain}/tts/audio"

    private fun headers(): Map<String, String> =
        mapOf("Authorization" to config.authHeader(), "Content-Type" to "application/json")

    private fun body(text: String): String =
        """{"text":${quote(text)},"format":"mp3","purpose":"course_essence"}"""

    private fun quote(value: String): String =
        buildString {
            append('"')
            value.forEach { c ->
                when (c) {
                    '\\' -> append("\\\\")
                    '"' -> append("\\\"")
                    '\n' -> append("\\n")
                    '\r' -> append("\\r")
                    '\t' -> append("\\t")
                    else -> append(c)
                }
            }
            append('"')
        }

}

private val ttsJson = Json { ignoreUnknownKeys = true; isLenient = true }

private fun parseObject(body: String): JsonObject? =
    try { ttsJson.parseToJsonElement(body).jsonObject } catch (_: Exception) { null }

private fun JsonObject.obj(key: String): JsonObject? = this[key] as? JsonObject
private fun JsonObject.str(key: String): String? = (this[key] as? JsonPrimitive)?.contentOrNull
