package com.classmate.core.official

enum class OfficialCapabilityTier {
    PRODUCT_FACING,
    DEV_LAB_SMOKE,
    EXCLUDED,
}

enum class OfficialCapabilityStatus {
    PRODUCT_READY,
    INTEGRATED,
    SEAM_READY,
    SMOKE_ONLY,
    EXCLUDED,
    CONFIG_MISSING,
}

data class OfficialCapability(
    val id: String,
    val docId: Int,
    val displayName: String,
    val officialTitle: String,
    val tier: OfficialCapabilityTier,
    val status: OfficialCapabilityStatus,
    val cloudPath: String,
    val onDeviceFallback: String,
    val manualFallback: String,
    val userVisibleLabel: String,
    val developerNotes: String,
    val safeSmokeAllowed: Boolean,
    val includedInAllSafeSmoke: Boolean = false,
) {
    val productFacing: Boolean get() = tier == OfficialCapabilityTier.PRODUCT_FACING
    val excluded: Boolean get() = tier == OfficialCapabilityTier.EXCLUDED
}

object VivoOfficialProviderRegistry {
    val all: List<OfficialCapability> = listOf(
        product(
            id = "LARGE_MODEL",
            docId = 1745,
            displayName = "大模型 / 文本生成",
            officialTitle = "大模型",
            status = OfficialCapabilityStatus.INTEGRATED,
            cloudPath = "云端蓝心 / qwen3.5-plus",
            onDeviceFallback = "端侧 BlueLM 3B",
            manualFallback = "安全占位 / 本地模板整理",
            userVisibleLabel = "云端蓝心",
            developerNotes = "CourseAnalysis / Ask / Practice / Review / Export share the Cloud -> On-device -> Manual routing policy.",
        ),
        product(
            id = "FUNCTION_CALLING",
            docId = 1805,
            displayName = "Function calling",
            officialTitle = "Function calling",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "云端 tool proposal adapter",
            onDeviceFallback = "端侧只给建议，不直接执行工具",
            manualFallback = "用户确认按钮",
            userVisibleLabel = "受控工具调用",
            developerNotes = "Official function-calling output adapts to InternalFunctionRouter; state-changing tools require confirmation.",
            includedInAllSafeSmoke = true,
        ),
        smoke(
            id = "IMAGE_GENERATION",
            docId = 1732,
            displayName = "图片生成",
            officialTitle = "图片生成",
            developerNotes = "Dev-lab only for future study-card visuals; not part of the learning evidence chain.",
        ),
        product(
            id = "TRANSLATION",
            docId = 1733,
            displayName = "文本翻译",
            officialTitle = "文本翻译",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "官方文本翻译 provider",
            onDeviceFallback = "端侧/云端大模型翻译草稿",
            manualFallback = "用户手动补充双语注记",
            userVisibleLabel = "翻译辅助学习",
            developerNotes = "Creates derived notes for evidence and knowledge points; original evidence remains unchanged.",
            includedInAllSafeSmoke = true,
        ),
        product(
            id = "EMBEDDING",
            docId = 1734,
            displayName = "文本向量",
            officialTitle = "文本向量",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "官方文本向量 provider",
            onDeviceFallback = "本地检索继续可用",
            manualFallback = "关键词检索",
            userVisibleLabel = "文本向量检索增强",
            developerNotes = "Parser/seam only; no vector database is required for the current release.",
        ),
        product(
            id = "TTS",
            docId = 1735,
            displayName = "音频生成 / TTS",
            officialTitle = "音频生成",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "官方 TTS provider",
            onDeviceFallback = "端侧生成课程精华脚本",
            manualFallback = "导出脚本文本",
            userVisibleLabel = "课程精华音频",
            developerNotes = "Only generic course essence audio. No real-person timbre or clone workflow.",
            includedInAllSafeSmoke = true,
        ),
        product(
            id = "OCR",
            docId = 1737,
            displayName = "通用 OCR",
            officialTitle = "通用 OCR",
            status = OfficialCapabilityStatus.INTEGRATED,
            cloudPath = "官方 OCR",
            onDeviceFallback = "端侧多模态语义草稿",
            manualFallback = "用户编辑/补充文字",
            userVisibleLabel = "图片文字识别",
            developerNotes = "Image/camera import keeps OCR text and on-device semantic draft as two tracks.",
            includedInAllSafeSmoke = true,
        ),
        smoke(
            id = "SHORT_ASR",
            docId = 1738,
            displayName = "实时短语音识别",
            officialTitle = "实时短语音识别",
            developerNotes = "Smoke/evaluation only; do not claim real-time classroom ASR is complete.",
        ),
        product(
            id = "ASR_LONG",
            docId = 1739,
            displayName = "长语音转写",
            officialTitle = "长语音转写",
            status = OfficialCapabilityStatus.INTEGRATED,
            cloudPath = "官方长语音转写",
            onDeviceFallback = "系统/端侧可用时作为辅助草稿",
            manualFallback = "粘贴转写文本",
            userVisibleLabel = "长语音转写",
            developerNotes = "Primary audio import path; creates editable TranscriptDraft and requires user confirmation.",
            includedInAllSafeSmoke = true,
        ),
        smoke(
            id = "LONG_DICTATION",
            docId = 1740,
            displayName = "长语音听写",
            officialTitle = "长语音听写",
            developerNotes = "Secondary ASR candidate for comparison with long transcription.",
        ),
        product(
            id = "ON_DEVICE_3B",
            docId = 1802,
            displayName = "端侧 3B 大模型",
            officialTitle = "端侧 3B 大模型",
            status = OfficialCapabilityStatus.INTEGRATED,
            cloudPath = "云端蓝心优先",
            onDeviceFallback = "端侧 BlueLM 3B",
            manualFallback = "安全占位 / 用户编辑",
            userVisibleLabel = "端侧 BlueLM 3B",
            developerNotes = "On-device fallback for generation and image semantic draft. It is not OCR or ASR.",
        ),
        product(
            id = "ON_DEVICE_FILES",
            docId = 1803,
            displayName = "端侧能力相关文件",
            officialTitle = "端侧能力相关文件",
            status = OfficialCapabilityStatus.INTEGRATED,
            cloudPath = "云端可继续服务",
            onDeviceFallback = "本地模型目录与 AAR 策略",
            manualFallback = "诊断说明",
            userVisibleLabel = "端侧模型文件诊断",
            developerNotes = "AAR and model files are local-only artifacts and must not be committed.",
        ),
        product(
            id = "ON_DEVICE_TEXT_SAFETY",
            docId = 1804,
            displayName = "端侧文本审核",
            officialTitle = "端侧文本审核",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "可选云端审核不在当前主链",
            onDeviceFallback = "端侧文本安全 seam",
            manualFallback = "温和风险提示",
            userVisibleLabel = "文本安全检查",
            developerNotes = "Unavailable does not block core learning; risky results warn before export/share.",
        ),
        product(
            id = "TEXT_SIMILARITY",
            docId = 2060,
            displayName = "文本相似度",
            officialTitle = "文本相似度",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "官方文本相似度 rerank",
            onDeviceFallback = "本地证据排序",
            manualFallback = "关键词检索",
            userVisibleLabel = "证据相似度排序",
            developerNotes = "Optional rerank for Ask evidence and practice/review evidence matching.",
            includedInAllSafeSmoke = true,
        ),
        product(
            id = "QUERY_REWRITE",
            docId = 2061,
            displayName = "查询改写",
            officialTitle = "查询改写",
            status = OfficialCapabilityStatus.SEAM_READY,
            cloudPath = "官方查询改写",
            onDeviceFallback = "端侧/本地问题整理",
            manualFallback = "使用原始问题",
            userVisibleLabel = "Ask 检索改写",
            developerNotes = "Optional Ask retrieval enhancer; original query remains the fallback.",
            includedInAllSafeSmoke = true,
        ),
        smoke(
            id = "DIALECT_ASR",
            docId = 2065,
            displayName = "方言自由说",
            officialTitle = "方言自由说",
            developerNotes = "Dev-lab ASR evaluation only.",
        ),
        smoke(
            id = "SIMULTANEOUS_INTERPRETATION",
            docId = 2068,
            displayName = "同声传译",
            officialTitle = "同声传译",
            developerNotes = "Dev-lab evaluation only; not a default learning path.",
        ),
        smoke(
            id = "VIDEO_GENERATION",
            docId = 2201,
            displayName = "视频生成",
            officialTitle = "视频生成",
            developerNotes = "Provider seam/smoke only; no real video generation in the product path.",
        ),
        excluded(
            id = "VOICE_CLONE",
            docId = 2062,
            displayName = "Excluded audio cloning capability",
            officialTitle = "Excluded audio cloning capability",
            developerNotes = "Excluded for consent and privacy risk. No product entry, no smoke, no task.",
        ),
        excluded(
            id = "GEO_POI",
            docId = 1736,
            displayName = "Excluded geocoding capability",
            officialTitle = "Excluded geocoding capability",
            developerNotes = "Excluded because it does not serve the core learning loop.",
        ),
    )

    val included: List<OfficialCapability> = all.filterNot { it.excluded }
    val productFacing: List<OfficialCapability> = all.filter { it.productFacing }
    val smokeOnly: List<OfficialCapability> = all.filter { it.tier == OfficialCapabilityTier.DEV_LAB_SMOKE }
    val excluded: List<OfficialCapability> = all.filter { it.excluded }
    val allSafeSmoke: List<OfficialCapability> = all.filter { it.includedInAllSafeSmoke }

    fun byId(id: String): OfficialCapability? =
        all.firstOrNull { it.id.equals(id, ignoreCase = true) }

    fun userSurfaceCapabilities(): List<OfficialCapability> =
        productFacing.filterNot { it.excluded }

    private fun product(
        id: String,
        docId: Int,
        displayName: String,
        officialTitle: String,
        status: OfficialCapabilityStatus,
        cloudPath: String,
        onDeviceFallback: String,
        manualFallback: String,
        userVisibleLabel: String,
        developerNotes: String,
        includedInAllSafeSmoke: Boolean = false,
    ) = OfficialCapability(
        id = id,
        docId = docId,
        displayName = displayName,
        officialTitle = officialTitle,
        tier = OfficialCapabilityTier.PRODUCT_FACING,
        status = status,
        cloudPath = cloudPath,
        onDeviceFallback = onDeviceFallback,
        manualFallback = manualFallback,
        userVisibleLabel = userVisibleLabel,
        developerNotes = developerNotes,
        safeSmokeAllowed = true,
        includedInAllSafeSmoke = includedInAllSafeSmoke,
    )

    private fun smoke(id: String, docId: Int, displayName: String, officialTitle: String, developerNotes: String) =
        OfficialCapability(
            id = id,
            docId = docId,
            displayName = displayName,
            officialTitle = officialTitle,
            tier = OfficialCapabilityTier.DEV_LAB_SMOKE,
            status = OfficialCapabilityStatus.SMOKE_ONLY,
            cloudPath = "explicit dev-lab smoke only",
            onDeviceFallback = "not part of the main learning path",
            manualFallback = "do not expose as a default user feature",
            userVisibleLabel = "开发实验能力",
            developerNotes = developerNotes,
            safeSmokeAllowed = true,
            includedInAllSafeSmoke = false,
        )

    private fun excluded(id: String, docId: Int, displayName: String, officialTitle: String, developerNotes: String) =
        OfficialCapability(
            id = id,
            docId = docId,
            displayName = displayName,
            officialTitle = officialTitle,
            tier = OfficialCapabilityTier.EXCLUDED,
            status = OfficialCapabilityStatus.EXCLUDED,
            cloudPath = "not used",
            onDeviceFallback = "not used",
            manualFallback = "not used",
            userVisibleLabel = "excluded",
            developerNotes = developerNotes,
            safeSmokeAllowed = false,
            includedInAllSafeSmoke = false,
        )
}
